[package]
name = "sass-rta"
version = "0.1.0"
authors = ["miyanokomiya <tomoya.hstexze24632@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.1"
regex = "1.3.9"
lazy_static = "1.4.0"
